### ISSUE TITLE
Xception Net

### ISSUE THREAD

**Issue by maarab-sfu** [KaidiXu/auto_LiRPA#9]
Hi,
I tried the framework on [Xception Net](https://github.com/Cadene/pretrained-models.pytorch/blob/master/pretrainedmodels/models/xception.py), and got the following errors:

`C:\Users\maarab\AppData\Local\Continuum\anaconda3\envs\batl-utils\lib\site-packages\torch\onnx\symbolic_helper.py:438: UserWarning: ONNX export mode is set to inference mode, but operator dropout is set to training  mode. The model will be exported in inference, as specified by the export mode.
  training_mode + ", as specified by the export mode.")
ERROR    10:37:59     The node has an unsupported operation: Node(name='/290', ori_name='', inputs=['/289'], attr={'ceil_mode': 0, 'kernel_shape': [3, 3], 'pads': [1, 1, 1, 1], 'strides': [2, 2]}, op='onnx::MaxPool', param=OrderedDict(), input_index=None, bound_node=None, output_index=0, perturbation=None)
ERROR    10:37:59     The node has an unsupported operation: Node(name='/302', ori_name='', inputs=['/301'], attr={'ceil_mode': 0, 'kernel_shape': [3, 3], 'pads': [1, 1, 1, 1], 'strides': [2, 2]}, op='onnx::MaxPool', param=OrderedDict(), input_index=None, bound_node=None, output_index=0, perturbation=None)
ERROR    10:37:59     The node has an unsupported operation: Node(name='/314', ori_name='', inputs=['/313'], attr={'ceil_mode': 0, 'kernel_shape': [3, 3], 'pads': [1, 1, 1, 1], 'strides': [2, 2]}, op='onnx::MaxPool', param=OrderedDict(), input_index=None, bound_node=None, output_index=0, perturbation=None)
ERROR    10:37:59     The node has an unsupported operation: Node(name='/430', ori_name='', inputs=['/429'], attr={'ceil_mode': 0, 'kernel_shape': [3, 3], 'pads': [1, 1, 1, 1], 'strides': [2, 2]}, op='onnx::MaxPool', param=OrderedDict(), input_index=None, bound_node=None, output_index=0, perturbation=None)
Traceback (most recent call last):
  File "simple_training.py", line 240, in <module>
    main(args)
  File "simple_training.py", line 207, in main
    model = BoundedModule(model_ori, dummy_input, bound_opts={'relu':args.bound_opts, 'conv_mode': args.conv_mode}, device=args.device)
  File "C:\Users\maarab\AppData\Local\Continuum\anaconda3\envs\batl-utils\lib\site-packages\auto_lirpa-0.1-py3.7.egg\auto_LiRPA\bound_general.py", line 34, in __init__
  File "C:\Users\maarab\AppData\Local\Continuum\anaconda3\envs\batl-utils\lib\site-packages\auto_lirpa-0.1-py3.7.egg\auto_LiRPA\bound_general.py", line 458, in _convert
  File "C:\Users\maarab\AppData\Local\Continuum\anaconda3\envs\batl-utils\lib\site-packages\auto_lirpa-0.1-py3.7.egg\auto_LiRPA\bound_general.py", line 357, in _convert_nodes
TypeError: __init__() takes 7 positional arguments but 9 were given`

Could tell me how can I fix the problem?

**Comment by shizhouxing** [comment]
Hi @maarab-sfu , it is because currently the `MaxPool` operation is not yet supported in our library. It seems that `MaxPool` could probably yield loose bounds for linear relaxation. I wonder if it is possible for you to replace the max pooling with average pooling?

**Comment by maarab-sfu** [comment]
> Hi @maarab-sfu , it is because currently the `MaxPool` operation is not yet supported in our library. It seems that `MaxPool` could probably yield loose bounds for linear relaxation. I wonder if it is possible for you to replace the max pooling with average pooling in the model?

Thanks for the response. I did that and now I get another error which does not make sense to me as I only change ResNet to XceptionNet (after changing maxpool to avg pool). Here is the error:
`Traceback (most recent call last):
  File "simple_training.py", line 256, in <module>
    main(args)
  File "simple_training.py", line 223, in main
    model = BoundedModule(model_ori,dummy_input,bound_opts = {'relu':args.bound_opts, 'conv_mode': args.conv_mode}, device = args.device)
  File "C:\Users\maarab\AppData\Local\Continuum\anaconda3\envs\batl-utils\lib\site-packages\auto_lirpa-0.1-py3.7.egg\auto_LiRPA\bound_general.py", line 34, in __init__
  File "C:\Users\maarab\AppData\Local\Continuum\anaconda3\envs\batl-utils\lib\site-packages\auto_lirpa-0.1-py3.7.egg\auto_LiRPA\bound_general.py", line 463, in _convert
  File "C:\Users\maarab\AppData\Local\Continuum\anaconda3\envs\batl-utils\lib\site-packages\auto_lirpa-0.1-py3.7.egg\auto_LiRPA\bound_general.py", line 360, in _convert_nodes
TypeError: __init__() takes 2 positional arguments but 9 were given`

On a seperate problem. I also get error when I try to change the number of classes. It seems that somewhere in the code, it has been assumed the number of classes in datasets are always 10.

**Comment by shizhouxing** [comment]
@maarab-sfu  Thanks for the information! It seems like a problem with unimplemented bounds for `onnx::GlobalAveragePool`, similarly raised in issue #7 . It is involved at `F.adaptive_avg_pool2d` in the Xception model. We will try to support this pooling soon. Meanwhile we hav supported `F.avg_pool2d` as used in https://github.com/KaidiXu/auto_LiRPA/blob/master/examples/vision/models/wide_resnet_cifar.py#L99. Is it possible for you to temporarily use `F.avg_pool2d` in the model?

**Comment by maarab-sfu** [comment]
> @maarab-sfu Thanks for the information! It seems like a problem with unimplemented bounds for `onnx::GlobalAveragePool`, similarly raised in issue #7 . It is involved at `F.adaptive_avg_pool2d` in the Xception model. We will try to support this pooling soon. Meanwhile we have supported `F.avg_pool2d` as used in https://github.com/KaidiXu/auto_LiRPA/blob/master/examples/vision/models/wide_resnet_cifar.py#L99. Is it possible for you to temporarily use `F.avg_pool2d` in the model?

Great. I did the change and now the error is something else:

`Traceback (most recent call last):
  File "simple_training.py", line 256, in <module>
    main(args)
  File "simple_training.py", line 223, in main
    model = BoundedModule(model_ori,dummy_input,bound_opts = {'relu':args.bound_opts, 'conv_mode': args.conv_mode}, device = args.device)
  File "C:\Users\maarab\AppData\Local\Continuum\anaconda3\envs\batl-utils\lib\site-packages\auto_lirpa-0.1-py3.7.egg\auto_LiRPA\bound_general.py", line 34, in __init__
  File "C:\Users\maarab\AppData\Local\Continuum\anaconda3\envs\batl-utils\lib\site-packages\auto_lirpa-0.1-py3.7.egg\auto_LiRPA\bound_general.py", line 468, in _convert
  File "C:\Users\maarab\AppData\Local\Continuum\anaconda3\envs\batl-utils\lib\site-packages\auto_lirpa-0.1-py3.7.egg\auto_LiRPA\bound_general.py", line 145, in forward
  File "C:\Users\maarab\AppData\Local\Continuum\anaconda3\envs\batl-utils\lib\site-packages\auto_lirpa-0.1-py3.7.egg\auto_LiRPA\bound_ops.py", line 1324, in forward
RuntimeError: The size of tensor a (73) must match the size of tensor b (74) at non-singleton dimension 3`

**Comment by huanzhang12** [comment]
@maarab-sfu We have just made a new release with better pooling layer support. You can try the latest version of `auto_LiRPA` and see if the issue is still there? Thanks!
